orbs:
  circleci-cli: circleci/circleci-cli@0.1.9
jobs:
  example-job:
    docker:
      - image: ubuntu-latest
    steps:
      - circleci-cli/install
workflows:
  example-workflow:
    jobs:
      - example-job
